mysql:
  enabled: false
  ip: "localhost:3306"
  database-name: vanish
  username: username1
  password: badpassword!
chat:
  fake-join-on-vanish: true
  fake-leave-on-vanish: true
# by default the plugin will use the translatable minecraft message, it's suggested to
# only change this if you already have custom leave/join messages
remove-from-tablist: true
remove-from-server-list: true # May be spam-able by users who are not logged into the server.
remove-from-required-sleeping-players: true
remind-while-vanished: true
remind-interval-in-seconds: 10
prevent-messaging: true #only checks minecraft default commands
# How a vanished person should look for people with the vanish.view permission
view:
  change-tablist: true
  tablist-format: "<gray>[Hidden]</gray> <i><username</i>"
  glow-while-vanished: true
prevent-opening:
  - BARREL
  - CHEST
  - ENDER_CHEST
  - SHULKER_BOX
