mysql:
  enabled: false
  ip: "localhost:3306"
  database-name: vanish
  username: username1
  password: badpassword!
chat:
  fake-join: true
  fake-leave: true
# by default the plugin will use the translatable minecraft message, it's suggested to
# only change this if you already have custom leave/join messages
customize-format: false
# Plugin supported placeholders are <username> or <displayname> - but you can also use any placeholder from placeholder API
# by formatting it like <papi:placeholder> so <papi:player_displayname> instead of %player_displayname%
custom-join: "<yellow><displayname> has joined!"
custom-leave: "<gray><displayname> has left"
remove-from-tablist: true
remove-from-server-list: true # May be spam-able by users who are not logged into the server.
# How a vanished person should look for people with the vanish.view permission
view:
  change-tablist: true
  tablist-format: "<gray>[Hidden]</gray> <i><username</i>"
  glow-while-vanished: true
prevent-container-animations-for:
  - BARREL
  - CHEST
  - ENDER_CHEST
  - SHULKER_BOX
